### ISSUE TITLE
Create Badge for College of Blaiddwyn

### ISSUE THREAD

**Issue by exile42** [swarren/sca-devices-badges#1]
Many thanks for creating all of these Scalable devices for the shires and baronies of the Outlands! I would like to include in this list the College of Blaiddwyn, a group under the umbrella of the Barony of al-Barran.

http://wharrow.outlandsheralds.org/group_armory/images/blaiddwy.gif

**Comment by swarren** [comment]
I've pushed an initial version of the device. The fox could probably use a bit more work, but it's a reasonable start!
